# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 479e7c9fe35b0e5aa421f9da83e5f5ad3271ee7de51e9ae07be0f99935912541f5fcb7c54a744faf6ce8a00a2ffe90981c8b85c03b8277a60b24ba0a1e9e4387

test:
  secret_key_base: e36a018248bdc58f9cf09e87329344a4ff6d2ea7e64b63eefd4eb6448cccdb39c12d6fbf2cf4ebd2898f00c33498a5542ff7252054ee7a6f3b1d9f4e59b2bd1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
